#+TITLE: stMartinTest notes
#+AUTHOR: Gail Gong
#+DATE: 2012-09-20

#+LATEX_HEADER: \usepackage{amscd}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{multirow}
#+LATEX_HEADER: \usepackage[table]{xcolor}
#+LATEX_HEADER: \addtolength{\oddsidemargin}{-1.0in}
#+LATEX_HEADER: \addtolength{\evensidemargin}{-1.0in}
#+LATEX_HEADER: \addtolength{\textwidth}{2.0in}

#+LATEX_HEADER: \addtolength{\topmargin}{-1.5in}
#+LATEX_HEADER: \addtolength{\textheight}{2.3in}

#+STYLE:    <link rel="stylesheet" type="text/css" href="./html-skeleton.css" />
#+PROPERTY: session *R*
#+PROPERTY: cache no
#+PROPERTY: results output verbatim
#+PROPERTY: exports both
#+PROPERTY: tangle yes

# <<TOP>>


* 2012-09-20

** Mike
- To log in to the website
  ssh -i stmtest.pem ubuntu@ec2-54-245-119-78.us-west-2.compute.amazonaws.com
- Moved all the wordpress files to the top level directory.
- Cloned TheTwentytenStm from github.
- sudo chown -R www-data.www-data TheTwentytenStm
- Installed wp-cycle.

** Turn on website on laptop so I can compare to what I had before
Gail-Gongs-MacBook-Pro:~ gailgong$ cd /Applications/wordpress-3.4-0/
Gail-Gongs-MacBook-Pro:wordpress-3.4-0 gailgong$ ./ctlscript.sh start
localhost:8080/wordpress/wp-admin


** Login to wordpress website
http://ec2-54-245-119-78.us-west-2.compute.amazonaws.com/wp-admin
r
hint: stillmotion workshop


** Set up the TheTwentyTenStm stuff, including header, front page, and sidebar
dashboard
themes
1. activate TheTwentytenStm
2. upload header image
   themes > header > TheTwentytenStm/images/header-image-png > upload
3. turn off comments
   settings > discussion > check the following:
   Basically, turn off Allow people to post comments on new articles
4. Front page
   Some pictures of our family...
   [wp_cycle]
   Newsletter  Podcasts Photo Gallery Calendar
5. Set it to be the front page
   Settings > Reading > A static page > Some pictures of our family...
6. Adjust wp-cycle settings
   plugins > installed plugins > wp-cycle >
   width 700 height 467
   upload images; they can't be too large
   Ask Gail to export from lightroom quality 25% and reorder using bridge
7. Fix sidebar step 1
   widgets > primary widget area > recents posts > Announcements
   Remove everything except recent posts and search
8. Fix sidebar step 2
   plugins > add new > Floating Social Media Icon > install > activate
   Floating Social Media Settings > Theme 19
   Put in links for facebook, twitter and rss feed
   Display mode: Manual only (using shortcode or php code--will not
   float)
   update
9. Add the image sizes in settings > media
   - thumbnail 175 117
   - medium 233 157
   - large 350 233
   - was 1024 1024


** Organize files from Gerard

*** 2012-09-18 First batch for web suite - 3 files
Here are the three documents for the "Serving Others" menu.
 
5A What we do.  Needs a link completed to 5B
5B Grants Awarded.  Photo?
5C Davis Community Meals.  More photos?  

From Janet:
I just noticed one tiny mistake. At the vert bottom of 5B Grants
Awarded, the phrase Yolo Wayfarer Center is listed. Please delete it
as it is listed above under "regional." Sorry I did not catch that
before. 

Or we can catch it in the testing phase if that is easier for you.

*** 2012-09-18 Web site information - second batch - 6 files
Here is some more information to plug in under the Welcome / About us menu:
 
- 2A Welcome.  Needs 4 links coded.  Photo.
- 2B Address / Map.  Needs map inserted.  Photo - suggest outside of church.
- 2C Staff / Vestry.  Needs photo of Janie.
- 2E Ministries. Needs links to 2F(top of page) and 3D (bottom of page).   Needs photos.
- 2F Ministies Leaders.  Nothing needed.  
- 2I  Social Activities.  Needs photos
 
Two documents are left in this section: 2G and 2H.  They are due
shortly.

*** 2012-09-19 More web site files - 7 Files
Here are the Worship files. 
 
- 3A  Regular Services: Need links to Nursery doc and photos.  But
      photos should go after the service times.  
- 3B  Summer Services: Needs link to Nursery doc.  Photo?
- 3C  Holiday Services: Needs photos
- 3D  Music:  Needs Link to organ file (attached).
- 3E  Nursery:  Needs photos.
- 3F  Podcasts:  This is the list of podcasts in the format we have
  now.  The only request is to include an option to subscribe to the
  podcasts.  Is this possible? 

*** 2012-09-20 Ignore 4B
 
** Action items
From Gerard: add option to subscribe to podcasts.
